add-part-of: true
add-reviewers: true
add-tested: true
impersonate-approvers: true
ci-timeout: 60min
target-branch-health-check: true
oncall-fix-label: oncall fix
oncall-fix-auto-approve: true
gitlab-url: "https://gitlab.infiscale.dev"
project-regexp: "shutong/test-merge-bot"
auth-token: ""
ssh-key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  replace-with-private-key
  -----END OPENSSH PRIVATE KEY-----
