{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marge-bot.secretName" . }}
  labels:
    {{- include "marge-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.authToken }}: {{ .Values.secrets.authToken | quote }}
  {{- if not .Values.useHttps }}
  {{ .Values.secrets.keys.sshKey }}: {{ .Values.secrets.sshKey | quote }}
  {{- end }}
{{- end }}
