replicaCount: 1

image:
  repository: harbor.infiscale.dev/workflow/merge-bot
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

gitlabUrl: "https://gitlab.infiscale.dev"
useHttps: false

extraArgs:
  - --project-regexp=shutong/test-merge-bot
  - --ci-timeout=60min
  - --impersonate-approvers
  - --add-tested
  - --add-reviewers
  - --add-part-of

secrets:
  create: true
  existingSecret: ""
  authToken: ""
  sshKey: ""
  keys:
    authToken: MARGE_AUTH_TOKEN
    sshKey: MARGE_SSH_KEY

serviceAccountName: default

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
